/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mastermind_dauguet_bulteau;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author bulte
 */
public class Fenetre_de_Jeu extends javax.swing.JFrame {
    Joueur[] ListeJoueurs = new Joueur[2];
    Joueur joueurCourant;
    Grille grillejeu = new Grille();
    Cellule 

    
        
        
    /**
     * Creates new form Fenetre_de_Jeu
     */
    //
    int K=0;
    int j=0;
    String Texte= "Réacapitulatif des différents essaies";
    public Fenetre_de_Jeu() {
        initComponents();
        
        Panneau_grille.setVisible(true);
        //jButton_Argent.setIcon(img_Argent);
        String []test= new String[4];
        
        
        
        for (int b = 0;b < 12; b++) {
            for (int a = 4;  a >= 0; a--) {
                CelluleGraphique cellGraph = new CelluleGraphique(grillejeu.CellulesJeu[a][b]);
                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {

                        Cellule c = cellGraph.celluleAssociee;
                        if (j==4){
                            j=0;
                            
                        }
                        
                        test[j]=Boule;
                        j++;
                        if (j==4){
                            j=0;
                            String [] Commun= new String[2];
                            //Code = creationCode()
                            //int nb=CouleurCode(Code[], test[]);
                            //Commun=Placepareil(Code[],test[],nb);
                            String Newligne=System.getProperty("line.separator");
                            
                            K++;
                            Texte=(Texte + Newligne +  "Test " +K+ Newligne + Commun[0]+" en commun"+ Newligne + Commun[1]+" bien placé");
                            Message.setText(Texte);
                        }
                        
                        
                        c.Couleur.equals(Boule);
                        
                        
                        Panneau_grille.repaint();
                        String [] Commun;
                        
                    }
                    });
                Panneau_grille.add(cellGraph);
            }
        }
                
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panneau_grille = new javax.swing.JPanel();
        jButton_Vert = new javax.swing.JButton();
        jButton_Dore = new javax.swing.JButton();
        jButton_Bleu = new javax.swing.JButton();
        jButton_Violet = new javax.swing.JButton();
        jButton_Rouge = new javax.swing.JButton();
        jButton_Jaune = new javax.swing.JButton();
        jButton_Blanc = new javax.swing.JButton();
        jButton_Argent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Message = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panneau_grille.setForeground(new java.awt.Color(111, 111, 151));
        Panneau_grille.setToolTipText("");
        Panneau_grille.setPreferredSize(new java.awt.Dimension(900, 300));
        Panneau_grille.setLayout(new java.awt.GridLayout());
        getContentPane().add(Panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 900, 300));

        jButton_Vert.setText("jButton1");
        jButton_Vert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VertActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Vert, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, 120));

        jButton_Dore.setText("jButton1");
        jButton_Dore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DoreActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Dore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 120));

        jButton_Bleu.setText("jButton1");
        jButton_Bleu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BleuActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Bleu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, 120));

        jButton_Violet.setText("jButton1");
        jButton_Violet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VioletActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Violet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 120, 120));

        jButton_Rouge.setText("jButton1");
        jButton_Rouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RougeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Rouge, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 120));

        jButton_Jaune.setText("jButton1");
        jButton_Jaune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_JauneActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Jaune, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, 120));

        jButton_Blanc.setText("jButton1");
        jButton_Blanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BlancActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Blanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 120, 120));

        jButton_Argent.setText("jButton1");
        jButton_Argent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ArgentActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Argent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 120, 120));

        Message.setColumns(20);
        Message.setRows(5);
        jScrollPane1.setViewportView(Message);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 280, 140));

        setBounds(0, 0, 1243, 636);
    }// </editor-fold>//GEN-END:initComponents
    int i=0;
    String Boule;
    ImageIcon img_Argent = new javax.swing.ImageIcon(getClass().getResource("Images/Bouleargent.png"));
    ImageIcon img_Blanche = new javax.swing.ImageIcon(getClass().getResource("Images/Bouleblanche.png"));
    ImageIcon img_Bleu = new javax.swing.ImageIcon(getClass().getResource("Images/Boulebleu.png"));
    ImageIcon img_Dore = new javax.swing.ImageIcon(getClass().getResource("Images/Bouledore.png"));
    ImageIcon img_Jaune = new javax.swing.ImageIcon(getClass().getResource("Images/Boulejaune.png"));
    ImageIcon img_Rouge = new javax.swing.ImageIcon(getClass().getResource("Images/Boulerouge.png"));
    ImageIcon img_Verte = new javax.swing.ImageIcon(getClass().getResource("Images/Bouleverte.png"));
    ImageIcon img_Violette = new javax.swing.ImageIcon(getClass().getResource("Images/Bouleviolette.png"));
    
    private void jButton_RougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RougeActionPerformed
        // TODO add your handling code here:
        
        
        Boule="Rouge";
        i=i+1;
    }//GEN-LAST:event_jButton_RougeActionPerformed

    private void jButton_VertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VertActionPerformed
        // TODO add your handling code here:
        i++;
        Boule="Vert";
    }//GEN-LAST:event_jButton_VertActionPerformed

    private void jButton_DoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DoreActionPerformed
        // TODO add your handling code here:
        i++;
        Boule="Dore";
    }//GEN-LAST:event_jButton_DoreActionPerformed

    private void jButton_BleuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BleuActionPerformed
        // TODO add your handling code here:
        i++;
        Boule="Bleu";
    }//GEN-LAST:event_jButton_BleuActionPerformed

    private void jButton_JauneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_JauneActionPerformed
        // TODO add your handling code here:
        i++;
        Boule="Jaune";
    }//GEN-LAST:event_jButton_JauneActionPerformed

    private void jButton_BlancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BlancActionPerformed
        // TODO add your handling code here:
        i++;
        Boule="Blanc";
    }//GEN-LAST:event_jButton_BlancActionPerformed

    private void jButton_VioletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VioletActionPerformed
        // TODO add your handling code here:
        i++;
        Boule="Violet";
    }//GEN-LAST:event_jButton_VioletActionPerformed

    private void jButton_ArgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ArgentActionPerformed
        // TODO add your handling code here:
        i++;
        Boule="Argent";
    }//GEN-LAST:event_jButton_ArgentActionPerformed

    /**
     * @param args the command line arguments
     */
    
    String [] code = new String [4];
    public String [] creationCode(){
    int var;
    String boule="rien";
    Random Aleat = new Random();
    for (int i=0; i<4; i++){
        var = Aleat.nextInt(8);
        if (var==1){
            boule="Argent";
        }
        if (var==2){
            boule="Rouge";
        }
        if (var==3){
            boule="Dore";
        }
        if (var==4){
            boule="Vert";
        }
        if (var==5){
            boule="Blanc";
        }
        if (var==6){
            boule="Bleu";
        }
        if (var==7){
            boule="Jaune";
        }
        if (var==8){
            boule="Violet";
        }
        code[i]= boule;
    }
    return code;
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Fenetre_de_Jeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Message;
    private javax.swing.JPanel Panneau_grille;
    private javax.swing.JButton jButton_Argent;
    private javax.swing.JButton jButton_Blanc;
    private javax.swing.JButton jButton_Bleu;
    private javax.swing.JButton jButton_Dore;
    private javax.swing.JButton jButton_Jaune;
    private javax.swing.JButton jButton_Rouge;
    private javax.swing.JButton jButton_Vert;
    private javax.swing.JButton jButton_Violet;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setIcon(ImageIcon img_Argent) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}

