/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mastermind_dauguet_bulteau;

/**
 *
 * @author bulte
 */
public class Fenetre_de_Jeu extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre_de_Jeu
     */
    public Fenetre_de_Jeu() {
        initComponents();
        Panneau_grille.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panneau_grille = new javax.swing.JPanel();
        jButton_Vert = new javax.swing.JButton();
        jButton_Dore = new javax.swing.JButton();
        jButton_Bleu = new javax.swing.JButton();
        jButton_Violet = new javax.swing.JButton();
        jButton_Rouge = new javax.swing.JButton();
        jButton_Jaune = new javax.swing.JButton();
        jButton_Blanc = new javax.swing.JButton();
        jButton_Argent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panneau_grille.setForeground(new java.awt.Color(111, 111, 151));
        Panneau_grille.setToolTipText("");

        javax.swing.GroupLayout Panneau_grilleLayout = new javax.swing.GroupLayout(Panneau_grille);
        Panneau_grille.setLayout(Panneau_grilleLayout);
        Panneau_grilleLayout.setHorizontalGroup(
            Panneau_grilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        Panneau_grilleLayout.setVerticalGroup(
            Panneau_grilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(Panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 900, 390));

        jButton_Vert.setText("jButton1");
        getContentPane().add(jButton_Vert, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, 120));

        jButton_Dore.setText("jButton1");
        getContentPane().add(jButton_Dore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 120));

        jButton_Bleu.setText("jButton1");
        getContentPane().add(jButton_Bleu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, 120));

        jButton_Violet.setText("jButton1");
        getContentPane().add(jButton_Violet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 120, 120));

        jButton_Rouge.setText("jButton1");
        getContentPane().add(jButton_Rouge, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 120));

        jButton_Jaune.setText("jButton1");
        getContentPane().add(jButton_Jaune, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, 120));

        jButton_Blanc.setText("jButton1");
        getContentPane().add(jButton_Blanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 120, 120));

        jButton_Argent.setText("jButton1");
        getContentPane().add(jButton_Argent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 120, 120));

        setBounds(0, 0, 1243, 636);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_de_Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre_de_Jeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panneau_grille;
    private javax.swing.JButton jButton_Argent;
    private javax.swing.JButton jButton_Blanc;
    private javax.swing.JButton jButton_Bleu;
    private javax.swing.JButton jButton_Dore;
    private javax.swing.JButton jButton_Jaune;
    private javax.swing.JButton jButton_Rouge;
    private javax.swing.JButton jButton_Vert;
    private javax.swing.JButton jButton_Violet;
    // End of variables declaration//GEN-END:variables
}
